name: frame_found_app
description: "App de busca de filmes usando a API do OMDB."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  lottie: ^3.3.1

  provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/lotties/